<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);ASPIRE010;ASPIRECERTIFICATES001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Sigstore.Bootstrap/Sigstore.Bootstrap.csproj" />
  </ItemGroup>

</Project>
