server {
    listen 8080;
    server_name _;

    location = /healthz {
        default_type application/json;
        return 200 '{"status":"SERVING"}';
    }

    location = /trusted_root.json {
        alias /var/lib/sigstore/tuf/active/targets/trusted_root.json;
        add_header Cache-Control "no-store";
    }

    location = /signing_config.v0.2.json {
        alias /var/lib/sigstore/tuf/active/targets/signing_config.v0.2.json;
        add_header Cache-Control "no-store";
    }

    location = /client_trust_config.json {
        alias /var/lib/sigstore/tuf/active/targets/client_trust_config.json;
        add_header Cache-Control "no-store";
    }

    location / {
        root /var/lib/sigstore/tuf/active/repository;
        try_files $uri =404;
        add_header Cache-Control "no-store";
    }
}
