server {
    listen 8080;
    server_name _;

    location = /healthz {
        default_type application/json;
        return 200 '{"status":"SERVING"}';
    }

    location = /trusted_root.json {
        alias /usr/share/nginx/bootstrap/trusted_root.json;
        add_header Cache-Control "no-store";
    }

    location = /signing_config.v0.2.json {
        alias /usr/share/nginx/bootstrap/signing_config.v0.2.json;
        add_header Cache-Control "no-store";
    }

    location = /client_trust_config.json {
        alias /usr/share/nginx/bootstrap/client_trust_config.json;
        add_header Cache-Control "no-store";
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri =404;
        add_header Cache-Control "no-store";
    }
}
